### ISSUE TITLE
Crash error after renaming to Hue-xxx

### ISSUE THREAD

**Issue by Tweaqer** [athombv/nl.philips.hue#23]
I've renamed my hue lights to 'hue-xxx' but now the hue app is crashed and showing this error:

```
Stack trace:

Error: The required argument 'name' is missing a value
at /node_modules/node-hue-api/hue-api/commands/traits/tBodyArguments.js:77:39
at Array.forEach (native)
at Object.Trait.buildRequestBody (/node_modules/node-hue-api/hue-api/commands/traits/tBodyArguments.js:67:49)
at buildOptions (/node_modules/node-hue-api/hue-api/httpPromise.js:38:20)
at Object.module.exports.invoke (/node_modules/node-hue-api/hue-api/httpPromise.js:121:17)
at HueApi.setLightName (/node_modules/node-hue-api/hue-api/index.js:317:24)
at Object.bridge.lights.(anonymous function).lights.(anonymous function).setLightName (/drivers/bulb/driver.js:630:28)
at Object.self.renamed (/drivers/bulb/driver.js:266:9)
at /homey-app/manager/drivers.js:197:20
at Object.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:131:9)

Exit code: 0
```
Homey Firmware Version: 0.10.0
Philips Hue v1.0.5

Update: after a reboot everything seemed fine again

**Comment by BasKiers** [comment]
This was a firmware issue, will be fixed in 0.10.1. Thanks for reporting
