### ISSUE TITLE
2 crashes in 3 days.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/nl.philips.hue#81]
Hue app crashed 2 times in the past 3 days.

I didn't check first crash info.

Now it is:

Stack trace:

[error] [DriverBulb] { Error: Philips Hue: 201, parameter, hue, is not modifiable. Device is set to off.
at getHttpClient.request.then.response (/node_modules/huejay/lib/Transport.js:69:21)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7) type: 201 }

[error] [DriverBulb] { Error: Philips Hue: 201, parameter, hue, is not modifiable. Device is set to off.
at getHttpClient.request.then.response (/node_modules/huejay/lib/Transport.js:69:21)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7) type: 201 }

Exit code: null
Exit signal: SIGKILL

**Comment by OpenMindNL** [comment]
Maybe a hint: I have one spare Hue Bulb. It's connected in the Hue App, but waiting in the box untill it's needed.

**Comment by WeeJeWel** [comment]
Should be fixed in v3.0.0
