### ISSUE TITLE
Hue app crashes after more than a week of no reboot of homey

### ISSUE THREAD

**Issue by satbopper** [athombv/nl.philips.hue#87]
always when i have a swapp file of lets see 450 mb the hue app starts crashing with the following reports

2017-10-12 01:17.40 nl.philips.hue (node:2347) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 bridge_001788fffe48e14d listeners added. Use emitter.setMaxListeners() to increase limit

2017-10-12 01:16:08 [err] [App] [Discovery] { Error: Huejay: Failed to get results from meethue
    at httpRequest.then.catch.response (/node_modules/huejay/lib/DiscoveryStrategy/Nupnp.js:43:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) type: undefined }

2017-10-12 01:17:13 [err] [App] [Discovery] { Error: Huejay: Failed to get results from meethue
    at httpRequest.then.catch.response (/node_modules/huejay/lib/DiscoveryStrategy/Nupnp.js:43:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) type: undefined }

2017-10-12 01:17:18 [err] [App] [Discovery] { Error: Huejay: Failed to get results from meethue
    at httpRequest.then.catch.response (/node_modules/huejay/lib/DiscoveryStrategy/Nupnp.js:43:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) type: undefined }
 and restarted with a gap of 5 min

**Comment by WeeJeWel** [comment]
Is this still happening? Seems like meethue.com couldn't be reached.

**Comment by satbopper** [comment]
sorry emile,i will close this because with the present firmware and hue version,for me no issue any more
